apiVersion: v1
kind: Service
metadata:
  name: mlops-client-service
spec:
  selector:
    app: mlops-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
      nodePort: 30002
  type: NodePort
